name: Feature Request
description: Suggest a new idea or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve this project!

  - type: input
    id: description
    attributes:
      label: Feature description
      description: What would you like to see added?
      placeholder: I want to support audio filters.

  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature useful?
      description: Explain the benefit or use case
      placeholder: This would allow audio EQ control for better sound.

  - type: checkboxes
    id: agreement
    attributes:
      label: Checklist
      options:
        - label: I checked that this feature does not exist yet.
          required: true
