name: Question or Support
description: Ask a question or request help
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Need help or have a question? Let us know!

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Describe your question or problem in detail.
      placeholder: I need help configuring the I2S output...
    validations:
      required: true
